function [phi_theoretical, mu_sorted] = BA_hybrid_genB_filter_sorted(A, B, b, k, lambda)
%BA_HYBRID_GENB_FILTER_SORTED
%  Theoretical hybrid BA–GMRES filter factors in the eigenbasis of M = BA,
%  valid for general B (not necessarily B = A').
%
%  We solve M x = d with
%      M = B*A (n x n),   d = B*b (n x 1),
%  by hybrid GMRES (Arnoldi–Tikhonov) with k steps and parameter lambda.
%
%  In the eigenbasis of M, M = S*Lambda*S^{-1}, exact solution x^dagger
%  has coordinates c = S^{-1} x^dagger, and with d = M x^dagger:
%      tilde_d = S^{-1} d = Lambda c  =>  c_i = tilde_d_i / mu_i.
%
%  The hybrid iterate can be written
%      x_k(λ) = sum_i φ_{i,k}(λ) c_i s_i,
%  with filter factors
%
%    φ_{i,k}(λ) =
%        [ μ_i / (tilde_d_i) ] * sum_{j=1}^k β1 ζ_j δ_j/(δ_j^2 + λ) c_{ij}^{(k)},
%
%  where:
%    μ_i        = eigenvalues of M = B*A,
%    tilde_d    = S^{-1} d = S^{-1} (B*b),
%    β1         = ||d||_2 = ||B*b||_2,
%    δ_j, ζ_j, c_{ij}^{(k)} are defined from the Arnoldi decomposition of M.
%
%  The eigenpairs (μ_i, s_i) are sorted by decreasing |μ_i|.
%
%  INPUT:
%    A      : m x n matrix
%    B      : n x m backprojector
%    b      : m x 1 RHS
%    k      : number of BA-GMRES steps
%    lambda : Tikhonov parameter
%
%  OUTPUT:
%    phi_theoretical : n x 1 vector of filter factors in eigenbasis of M=BA,
%                      ordered by decreasing |μ_i|.
%    mu_sorted       : n x 1 eigenvalues of M corresponding to phi_theoretical.
%
%  NOTE: This assumes BA_hybrid(A,B,b,k,lambda) returns, among others,
%        the Arnoldi matrix Hbar (size (k+1)xk) and the basis Qk (size n x k),
%        generated by applying GMRES/Arnoldi to M = B*A with starting vector d = B*b.

    % ---------- 0) Define M and d ----------
    M = B * A;        % n x n
    d = B * b;        % n x 1
    beta1 = norm(d);  % β1 = ||d||_2

    % ---------- 1) Eigen-decomposition of M and sorting by |mu| ----------
    [S, Lambda] = eig(M);
    mu = diag(Lambda);        % eigenvalues of M

    % Sort by descending |mu|
    [~, perm_mu] = sort(abs(mu), 'descend');
    mu_sorted = mu(perm_mu);
    S_sorted  = S(:, perm_mu);

    n_dim = length(mu_sorted);

    % ---------- 2) Arnoldi data from BA_hybrid ----------
    % BA_hybrid is assumed to run GMRES/Arnoldi on M = B*A with RHS d = B*b
    % and return Hbar (k+1 x k) and Qk (n x k).
    [~, ~, ~, Hbar, Qk, ~, ~, ~, ~] = BA_hybrid(A, B, b, k, lambda);
    % Hbar: (k+1) x k,  Qk: n x k

    % ---------- 3) Spectral decomposition of Hbar' * Hbar ----------
    HN = Hbar' * Hbar;           % k x k
    [Sk, Dk] = eig(HN);          % HN = Sk * Dk * Sk'
    delta = sqrt(max(diag(Dk), 0));  % reduced singular values δ_j >= 0

    % Sort δ_j in descending order and reorder Sk
    [delta, perm_delta] = sort(delta, 'descend');
    Sk = Sk(:, perm_delta);

    % ---------- 4) ζ_j ----------
    e1 = zeros(k+1, 1);
    e1(1) = 1;
    tmp = Sk' * (Hbar' * e1);    % k x 1 = (S_k^T Hbar^T e1)_j

    zeta = zeros(k,1);
    for j = 1:k
        if delta(j) > 0
            zeta(j) = tmp(j) / delta(j);
        else
            zeta(j) = 0;         % convention if δ_j = 0
        end
    end

    % ---------- 5) γ_j(λ) ----------
    % γ_j(λ) = β1 ζ_j δ_j / (δ_j^2 + λ)
    gamma = beta1 * zeta .* (delta ./ (delta.^2 + lambda));   % k x 1

    % ---------- 6) Couplings c_{ij}^{(k)} ----------
    %   W_k   = Q_k S_k          (n x k)
    %   C^k   = S_sorted^{-1} W_k    (n x k)
    %        = S_sorted^{-1} Q_k S_k
    %   sum_j γ_j c_{ij}^{(k)} = (C^k * gamma)_i.

    % Use the sorted eigenvector matrix S_sorted
    C_base = S_sorted \ Qk;        % n x k, solves S_sorted * X = Qk
    C      = C_base * Sk;          % n x k

    sum_part = C * gamma;          % n x 1

    % ---------- 7) Assemble φ_{i,k}^h(λ) ----------
    tilde_d = S_sorted \ d;        % n x 1, eigenbasis coords of d

    phi_theoretical = zeros(n_dim,1);
    for i = 1:n_dim
        if mu_sorted(i) ~= 0 && tilde_d(i) ~= 0
            % φ_i = μ_i / (tilde_d_i) * Σ_j γ_j c_{ij}^{(k)}
            phi_theoretical(i) = mu_sorted(i) * sum_part(i) / tilde_d(i);
        else
            phi_theoretical(i) = 0;
        end
    end
end
